### ISSUE TITLE
Provide release signatures

### ISSUE THREAD

**Issue by SirCmpwn** [facebook/yoga#272]
When you ship a release, can you sign it with PGP and include the signature?

**Comment by emilsjolander** [comment]
I'll manage releases via Github's releases feature which I think does this by default. First big release will come once I feel like I have address the major issues that popped up after launch.

**Comment by SirCmpwn** [comment]
GitHub releases do not do this automatically.

**Comment by emilsjolander** [comment]
This is quite a bit of extra work on each release. For now I don't think it is worth it but I can ofc be convinced otherwise 👍

**Comment by SirCmpwn** [comment]
Poor form from an organization like Facebook. Without signatures it's not possible to be confident in the authenticity of the releases.

**Comment by emilsjolander** [comment]
I'm not quite understanding. The source for the release is on github for you to verify with if you want. What would a pgp signature give beyond that?

**Comment by SirCmpwn** [comment]
Well, that puts the trust in GitHub, not in the developers. GitHub also doesn't provide checksums or anything like them. A state sponsored actor could probably trivially get a certificate to MitM your GitHub connection with, and many companies could do it to. Stupid software like Lenovo's superfish also calls SSL into question. PGP signatures are the gold standard in the open source community for verifying release tarballs. It's less common in the areas Facebook is used to but if you're writing software in C that ships on desktops you should probably familiarize yourselves with the mainstream release processes on that platform.

**Comment by emilsjolander** [comment]
As I don't know much about this could you link to a source? I'll look into it for the next release. Thanks!

**Comment by SirCmpwn** [comment]
I'm not sure what kind of source you'd like. This is how you do it:

```
gpg --gen-key # create a new key to sign with
gpg --export --armor [key id] # export the public key and share it with people
gpg --detach-sign --default-key [key id] release.tar.gz # create a signature
```

Attach release.tar.gz.asc to the release and you're done.

**Comment by emilsjolander** [comment]
Thanks! Follow up question. In the proposed scenario in which github is compromised it would not help to provide the signature unless I distribute the public key outside of github. Right? Which leads to the question, how is the public key typically distributed?

**Comment by emilsjolander** [comment]
Thanks for teaching me :) I'll make sure to do this for the 1.3 release.

**Comment by SirCmpwn** [comment]
Thanks!

**Comment by emilsjolander** [comment]
Done.
https://github.com/facebook/yoga/releases/tag/1.3.0
https://keybase.io/emilsj

**Comment by SirCmpwn** [comment]
Thanks! Signing the tag is still not quite the same... won't integrate very well with most tools that are expecting the tarball to be signed. I do signatures on GitHub like this:

https://github.com/SirCmpwn/sway/releases/tag/0.11

**Comment by emilsjolander** [comment]
Signing the tarball adds quite a bit of overhead because we don't actually publish a tarball (github generated one automatically). I went this something which solves the issue of secure releases while also making releases as easy as possible.

**Comment by SirCmpwn** [comment]
I just download the tarball from github and sign that, not too much overhead involved. Doing it this way means that package managers and such will likely have to clone the whole repository and use custom logic to verify the release signatures.

**Comment by SirCmpwn** [comment]
So?
