### ISSUE TITLE
YogaKit failing tests 

### ISSUE THREAD

**Issue by rmarinho** [facebook/yoga#337]
I have` testThatMarkingLeafsAsDirtyWillTriggerASizeRecalculation,  testFrameAndOriginPlacement and  testSizeThatFitsSmoke` failing for me on Xcode.. the values are not correct but seems a problem rounding ..

**Comment by dshahidehpour** [comment]
Hi @rmarinho, I'll take a look at this today. There has been a lot of churn in those files via PRs and internal fixes recently, so it's not unlikely something went amiss.

**Comment by dshahidehpour** [comment]
Working on this now.

**Comment by dshahidehpour** [comment]
Just put up an internal diff, I'll do my best to land this today, thanks for being patient!

**Comment by dshahidehpour** [comment]
Fixed in a4bab68

**Comment by 100mango** [comment]
Still fail in the newest master branch.

run in Xcode

![image](https://user-images.githubusercontent.com/5073511/87649557-0793ee80-c783-11ea-9cc7-d82b97c2fd6d.png)
