### ISSUE TITLE
NoClassDefFoundError: com/facebook/jni/Countable when load liblib_fb_fbjni.so in Andorid 4.2

### ISSUE THREAD

**Issue by Shuijwan** [facebook/yoga#354]
when run in Android 4.2, when Soloader.loadLibrary("yoga") is called, it crashes in 

I/dalvikvm(22627): java.lang.NoClassDefFoundError: com/facebook/jni/Countable
I/dalvikvm(22627): 	at java.lang.Runtime.nativeLoad(Native Method)
I/dalvikvm(22627): 	at java.lang.Runtime.load(Runtime.java:338)
I/dalvikvm(22627): 	at java.lang.System.load(System.java:521)
I/dalvikvm(22627): 	at com.facebook.soloader.DirectorySoSource.loadLibraryFrom(DirectorySoSource.java:71)
I/dalvikvm(22627): 	at com.facebook.soloader.DirectorySoSource.loadLibrary(DirectorySoSource.java:42)
I/dalvikvm(22627): 	at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:299)
I/dalvikvm(22627): 	at com.facebook.soloader.DirectorySoSource.loadLibraryFrom(DirectorySoSource.java:65)
I/dalvikvm(22627): 	at com.facebook.soloader.DirectorySoSource.loadLibrary(DirectorySoSource.java:42)
I/dalvikvm(22627): 	at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:299)
I/dalvikvm(22627): 	at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:247)

I/dalvikvm(22627): "main" prio=5 tid=1 NATIVE
I/dalvikvm(22627):   | group="main" sCount=0 dsCount=0 obj=0x417be9a0 self=0x414eb010
I/dalvikvm(22627):   | sysTid=22627 nice=0 sched=0/0 cgrp=apps handle=1074394076
I/dalvikvm(22627):   | state=R schedstat=( 389452864 433043120 139 ) utm=23 stm=15 core=0
I/dalvikvm(22627):   #00  pc 000012a0  /system/lib/libcorkscrew.so (unwind_backtrace_thread+27)
I/dalvikvm(22627):   #01  pc 0005faa8  /system/lib/libdvm.so (dvmDumpNativeStack(DebugOutputTarget const*, int)+35)
I/dalvikvm(22627):   #02  pc 00053914  /system/lib/libdvm.so (dvmDumpThreadEx(DebugOutputTarget const*, Thread*, bool)+303)
I/dalvikvm(22627):   #03  pc 000539ae  /system/lib/libdvm.so (dvmDumpThread(Thread*, bool)+25)
I/dalvikvm(22627):   #04  pc 00038aba  /system/lib/libdvm.so
I/dalvikvm(22627):   #05  pc 0003e97e  /system/lib/libdvm.so
I/dalvikvm(22627):   #06  pc 0000706a  /data/app-lib/flexbox.layoutmanagertestapp-1/liblib_fb_fbjni.so (facebook::jni::CountableOnLoad(_JNIEnv*)+33)
I/dalvikvm(22627):   #07  pc 0000a528  /data/app-lib/flexbox.layoutmanagertestapp-1/liblib_fb_fbjni.so (initialize_fbjni()+7)
I/dalvikvm(22627):   #08  pc 0000b48c  /data/app-lib/flexbox.layoutmanagertestapp-1/liblib_fb_fbjni.so (facebook::jni::initialize(_JavaVM*, std::function<void ()>&&)+387)
I/dalvikvm(22627):   #09  pc 0000beba  /data/app-lib/layoutmanagertestapp-1/liblib_fb_fbjni.so (JNI_OnLoad+49)

the JNI_OnLoad in fb's onload.cpp is trying to call CountablOnLoad which will find the Countable class, and the class is not exist. In Android N, there is no problem.

I am not sure if it is because in Android N, the liblib_fb_fbjni's JNI_OnLoad is not called?

**Comment by Shuijwan** [comment]
I dig into the fbjni code today, and find the root cause is that the NDK bug in android 4.2, the dependency library(here is the liblib_fb_fbjni.so depended by libyoga.so) need to be loaded explicitly, so the fbjni's JNI_Onload will be called, and in this JNI_OnLoad it will call initialize_fbjni.  The initialize_fbjni function seems useless, and it will crash in lack of Countable class.  After delete initialize_fbjni, It works on Android 4.2 now.

**Comment by emilsjolander** [comment]
Good find!

**Comment by kosiarska** [comment]
It still happens on android 4.2
with this versions of libraries:
` compile 'com.facebook.yoga.android:yoga-layout:1.4.1'
   compile 'com.facebook.soloader:soloader:0.2.0'`

**Comment by ToddAshmore** [comment]
@emilsjolander You stated "good find!", but didn't seem to post any solution this problem. Is there something that we can do on our end to make this work? We really would love to use Litho on our project, but can't do so unless we get this figured out for older devices. Thanks.

**Comment by emilsjolander** [comment]
Not sure why i closed this TBH. Re-opening as this is still an issue.

**Comment by emilsjolander** [comment]
Should be fixed with https://github.com/facebook/yoga/commit/76f6a54327837bd1d791528409b9b0704e37bb76 I'll create a new release at the end of the week.

**Comment by mucyomiller** [comment]
Am still facing this issue on android 4.x running newer version of litho 0.5.0 !???

**Comment by vinnybad** [comment]
+1, I'm seeing the same as @mucyomiller

**Comment by mucyomiller** [comment]
@emilsjolander  why do you closed this issue while  it's seem that this bug still exists yet!

**Comment by LeoSchleicher** [comment]
@emilsjolander I confirm that this issue is still present in 1.6.0 on Android 4.2.2

**Comment by zhoumingjun** [comment]
@emilsjolander I met the same issue today. please reopen it.

**Comment by lewic1987** [comment]
Hello, looking forward to using Litho in our project, but we found the same problem on the 4.2 system, please reopen it.

**Comment by mucyomiller** [comment]
@Shuijwan  how did you managed to overcome this bug?

**Comment by emilsjolander** [comment]
Sorry for the delay. Re-opening and looking into now.

**Comment by emilsjolander** [comment]
This was an issue with the litho repo and corresponding gradle and buck files. We could not fix it for buck on API 16 now (we tried but got stuck) however gradle will now work for those android versions. A  commit will be made soon to the litho repo. Thanks for pushing on this issue!

**Comment by LeoSchleicher** [comment]
My workaround was simply including 6kb jar with missing classes (com.facebook.jni.Countable and others from this package) in my project. And now yoga 1.6.0 works fine on 4.2.2

**Comment by LeoSchleicher** [comment]
This one
[libfb-release.zip](https://github.com/facebook/yoga/files/1344733/libfb-release.zip)

**Comment by zhaozheyu** [comment]
i met the same issue too！

**Comment by zhaozheyu** [comment]
i met the same issue too！
