### ISSUE TITLE
YGRoundToPixelGrid has accumulated error?

### ISSUE THREAD

**Issue by AugustRush** [facebook/yoga#545]
every time call YGNodeCalculateLayout function, cached node call 'YGRoundToPixelGrid' function  has accumulated lead to value's error (iOS).

**Comment by emilsjolander** [comment]
Can you give repro steps, or perhaps write a test case? Thanks!

**Comment by woehrl01** [comment]
@AugustRush I think this is fixed via b378a6. It would be great if you could give a short heads up, if this is the error you perceived.

**Comment by AugustRush** [comment]
This issue still exsit in my project, if i ignore this everytiing will be OK.

**Comment by woehrl01** [comment]
Could you please provide a deeper explanation? I didn't get the problem yet. As @emilsjolander suggested it would be highly appreciated if you could provide the necessary steps to reproduce the issue.

**Comment by AugustRush** [comment]
In my project, i use Yoga to layout all subviews on UITableViewCell , there has some buttons , every time i tapped the button , i need to mark the button's yoga property to 'dirty', it will re-layout and then this issue happened!

**Comment by woehrl01** [comment]
I'm still not 100% sure if I understand the problem correctly. But it sounds like yoga doesn't preserve the origin and shifts the layout around. Have a look at `applyLayoutPreservingOrigin` if this solves your problem. Otherwise you'll need to provide a code example to be able to assist you with that.

**Comment by woehrl01** [comment]
There have been a lot of fixes lately regarding accumulation errors in rounding. If you still see an issue, please reopen.
