### ISSUE TITLE
'algorithm' file not found (since RN 0.53)

### ISSUE THREAD

**Issue by Jpunt** [facebook/yoga#711]
# Report

- [x] I have searched [existing issues](https://github.com/facebook/yoga/issues) and this is not a duplicate

☝️ However, this is *very* similar to [this other issue](https://github.com/facebook/yoga/issues/697). Could it be possible to fix these kind of errors in a bit more structural way? 🤔 

# Issues and Steps to Reproduce
We've got this in our PodFile:

```rb
pod 'React', :path => 'node_modules/react-native', :subspecs => [
  'Core',
  'CxxBridge',
  'DevSupport',
  'RCTText',
  'RCTNetwork',
  'RCTWebSocket',
  'RCTImage',
  'RCTAnimation',
]
pod 'yoga', :path => 'node_modules/react-native/ReactCommon/yoga'
```

Prior to ReactNative 0.53 this worked. After upgrading to the latest it doesn't.

# Expected Behavior
A successful build

# Actual Behavior
This error:

![screen shot 2018-02-07 at 10 49 03](https://user-images.githubusercontent.com/190501/35909650-8b6e9ffe-0bf4-11e8-9b43-cdbb49c43e8f.png)

**Comment by ImL1s** [comment]
I have same problem...

**Comment by danieljvdm** [comment]
The following cocoapods post install script fixes the issue:

```
def remove_unused_yoga_headers
    filepath = './Pods/Target Support Files/yoga/yoga-umbrella.h'
    
    contents = []
    
    file = File.open(filepath, 'r')
    file.each_line do | line |
        contents << line
    end
    file.close
    
    contents.delete_at(14) # #import "YGNode.h"
    contents.delete_at(14) # #import "YGNodePrint.h"
    contents.delete_at(14) # #import "Yoga-internal.h"
    
    file = File.open(filepath, 'w') do |f|
        f.puts(contents)
    end
end

post_install do | installer |
    remove_unused_yoga_headers
end
```

**Comment by SanjayTCP** [comment]
I'm seeing this issue as well. After removing those lines in `yoga-umbrella.h`, I'm getting:

```
umbrella header for module 'yoga' does not include header 'YGNode.h' 
#import "Headers/yoga-umbrella.h"
^
<module-includes>:1:1: error: umbrella header for module 'yoga' does not include header 
<module-includes>:1:1: error: umbrella header for module 'yoga' does not include header 'Yoga-internal.h'
```

Which totally makes sense after removing those lines.

This seems to be an issue in RN 0.52.X as well:
https://github.com/facebook/yoga/issues/697

I think the only solution for me right now is to back-up to `0.51.0`.

**Comment by Jpunt** [comment]
The workaround from @danieljvdm seems to work. Would be nice if we don't need this kind of black magic though 😅

**Comment by MarkMolina** [comment]
Tried the 0.54.0-rc3 and still get the same error.

**Comment by krmao** [comment]
how to solve it ?

**Comment by danieljvdm** [comment]
@krmao read my comment

**Comment by krmao** [comment]
@danieljvdm  yes , thank you guy !

**Comment by justColbs** [comment]
Manually deleting the lines or adding the post install script does not solve it for me. I still get the same issue. I'm also upgrading my project from 0.45.0, maybe that has something to do with it?

**Comment by hitbear518** [comment]
https://github.com/facebook/react-native/pull/17764
see this pr

**Comment by justColbs** [comment]
@hitbear518 That worked for me, but then I get the fishhook error. I resolved that, and now I have another error. This feels like a slippery slope. The new error is in the image and because of that, I cannot `import React` anywhere in my project without it failing to build React.
 
![screen shot 2018-03-12 at 1 37 02 pm](https://user-images.githubusercontent.com/8528904/37300194-bd0a620c-25fb-11e8-8f9c-9df8e8ca956d.png)

**Comment by danieljvdm** [comment]
@justColbs this is a new error in 54.0, I spent a few hours trying to fix it but eventually gave up. Seem like there's illegal syntax in a bunch of new files

**Comment by justColbs** [comment]
@danieljvdm Smh. Thanks for the response. I'll try downgrading to 0.53 and cross my fingers.

**Comment by sarathkumarcr007** [comment]
I am having this imports in the "yoga-umbrella.h". what do I want to do?
`#import "Utils.h"
#import "YGEnums.h"
#import "Yoga-internal.h"
#import "Yoga.h"`

**Comment by amardeepranu** [comment]
@justColbs Removing the "&" from `minimumSize` and `maximumSize` from both `RCTSurfaceSizeMeasureMode.h` and `RCTSurfaceSizeMeasureMode.mm` allows me to build. Pretty sure this breaks the behaviour of that function since the minimumSize and maximumSize values will not be changed within that function, however I don't see this class being used anywhere. Thoughts?

**Comment by amardeepranu** [comment]
@danieljvdm  Removing the "&" from minimumSize and maximumSize from both RCTSurfaceSizeMeasureMode.h and RCTSurfaceSizeMeasureMode.mm allows me to build. Pretty sure this breaks the behaviour of that function since the minimumSize and maximumSize values will not be changed within that function, however I don't see this class being used anywhere. Thoughts?

**Comment by justColbs** [comment]
@amardeepranu No clue. I just downgraded to 0.53 and it didn't give me any more problems with this, other than the plethora of problems that have hacky solutions :)

**Comment by lemonkey** [comment]
Downgrading to react-native@0.53.0 didn't fix it for me (same algorithm error).
Downgrading to react-native@0.51.0 and react@16.0.0 didn't fix it for me either (this time fishhook error).

Welp.

**Comment by justColbs** [comment]
@lemonkey You can fix that fishhook error, but i'm not sure if you've tried it. #import "fishhook.h" should be the replacement. 

... I feel your pain. ha

**Comment by amardeepranu** [comment]
I encountered all the issues in this thread and was able to fix them with the following pod post-install script:

```
def fix_cplusplus_header_compiler_error
    filepath = '../node_modules/react-native/React/Base/Surface/SurfaceHostingView/RCTSurfaceSizeMeasureMode.h'

    contents = []

    file = File.open(filepath, 'r')
    file.each_line do | line |
        contents << line
    end
    file.close

    if contents[32].include? "&"
        contents.insert(26, "#ifdef __cplusplus")
        contents[36] = "#endif"

        file = File.open(filepath, 'w') do |f|
            f.puts(contents)
        end
    end
end

def fix_unused_yoga_headers
    filepath = './Pods/Target Support Files/yoga/yoga-umbrella.h'

    contents = []

    file = File.open(filepath, 'r')
    file.each_line do | line |
        contents << line
    end
    file.close

    if contents[12].include? "Utils.h"
        contents.delete_at(15) # #import "YGNode.h"
        contents.delete_at(15) # #import "YGNodePrint.h"
        contents.delete_at(15) # #import "Yoga-internal.h"
        contents.delete_at(12) # #import "Utils.h"

        file = File.open(filepath, 'w') do |f|
            f.puts(contents)
        end
    end
end

def react_native_fix
    fix_cplusplus_header_compiler_error
    fix_unused_yoga_headers
end

post_install do |installer|
    react_native_fix
end
```

Also used this fix for the fishhook error: https://github.com/facebook/react-native/issues/16039#issuecomment-351100376

**Comment by lemonkey** [comment]
@justColbs Was able to go forward with react-native@0.53.0 and react@16.2.0 with the fishhook.h import fix, thanks.

**Comment by Jpunt** [comment]
FYI: This is still an issue on 0.54.

```
Environment:
  OS: macOS High Sierra 10.13.3
  Node: 8.2.1
  Yarn: 0.27.5
  npm: 5.3.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: ^16.2.0 => 16.2.0
  react-native: ^0.54.2 => 0.54.2
```

**Comment by lemonkey** [comment]
@amardeepranu Thanks, confirming that your Podfile post-install step along with the package.json postinstall Fishhook fix worked for me with react-native@0.54.2 and react@^16.3.0-alpha.1 (latest as I write this).

**Comment by oceanbin** [comment]
how fix it on android gradle

**Comment by Jpunt** [comment]
This is **still** an issue in RN 0.54.4:

```
Environment:
  OS: macOS High Sierra 10.13.3
  Node: 8.2.1
  Yarn: 1.5.1
  npm: 5.3.0
  Watchman: 4.9.0
  Xcode: Xcode 9.3 Build version 9E145
  Android Studio: 3.1 AI-173.4670197

Packages: (wanted => installed)
  react: ^16.3.0 => 16.3.0
  react-native: ^0.54.4 => 0.54.4
```

![screen shot 2018-04-03 at 14 02 48](https://user-images.githubusercontent.com/190501/38248169-cdee05f8-3747-11e8-9866-c529971d52d9.png)

**Comment by ucerxxx** [comment]
yoga-umbrella.h file should have only three imports: `#import "Yoga.h"
#import "YGEnums.h"
#import "YGMacros.h"`

There are three ways to achieve it: 
1. Fix it manually after pods are built
2. Fix yoga.podspec manually or using patch: [https://gist.github.com/ucerxxx/7101eb87240ccb098a8a9093b421c6fe](url)
3. Add script in podfile in post_install similar to @amardeepranu post

**Comment by no-NameTillNow** [comment]
Workarounds for all integrating issues
1.'algorithm' file not found and yoga/Yoga.h missing
spec.public_header_files = 'yoga/Yoga.h', 'yoga/YGEnums.h', 'yoga/YGMacros.h'
then do 'Pod install'
2.there some issues regarding typedef and NSAttributedKeyString ,which u can solve by the hints xcode provides
3.After doing step 1 & 2 build, again there will be error ,now 
if there is an error with 'folly/folly-config.h' just deleted node_modules and uninstall react-native then agin install react-native
also delete ur Deriveddata of xcode (rm -rfd ~/Library/Development/Xcode/DerivedData)
else if there is error pointing @ CGSize &minimum in RCTSurfaceSizeMeasureMode.h  then,
add "ifdef _cpluscplus" before RCT_EXTERN func and add "#endif" after func close
4.clean and build 
All errors will be cleared
Hope it works
P.S: whenever you do pod install clean ur project and then run

**Comment by ibrahimab** [comment]
Can someone from the core team explain why this is still happening?

**Comment by laibinCN** [comment]
@ibrahimab This question has been going on for a long time.

**Comment by laibinCN** [comment]
@no-NameTillNow 
It means that I,in "RCTSurfaceHostingView.h" file.
`Use of undeclared identifier 'RCTSurfaceMinimumSizeAndMaximumSizeFromSizeAndSizeMeasureMode'
`

**Comment by Jpunt** [comment]
After a lot of struggling, I came down to [these additions to our Podfile](https://gist.github.com/Jpunt/3fe75effd54a702034b75ff697e47578), which is a combination of a lot of workarounds from this and other issues 😒

**Comment by NrqhEIcsRi004** [comment]
Change  use_frameworks! ==> #  use_frameworks! ?

**Comment by orta** [comment]
I have a shared project for hot fixing React Native versions for issues like this: https://github.com/orta/cocoapods-fix-react-native

**Comment by sarath-rp** [comment]
In my case add this line to yoga.podspec file
` spec.public_header_files = 'yoga/Yoga.h', 'yoga/YGEnums.h', 'yoga/YGMacros.h'`

**Comment by sospedra** [comment]
Still broken with RN 0.55.4

**Comment by ibrahimab** [comment]
Since 0.55.4 I can delete React and the other packages from Cocoapods, most packages I use have updated their repo so React 0.11 won't install. 

Still, can one of the contributors explain why some of the third party packages causes cocoapods installs another version of React and how we can fix this without defining it in the Podfile. The reason I ask is because when I do this in my projects everything goes wrong and, even while including DevSupport in the subspecs, shaking to open dev menu will not work.

Maybe an issue should be opened to expand the documentation to tackle this problem that many developers are facing, especially if those developers haven't heard of this repo: https://github.com/orta/cocoapods-fix-react-native

Can I get an official reaction from the React Native Core Team? I am happy to contribute but I would love to know what is causing this and whether you are working on this.

I am tagging the only contributor I know actively answers questions: @hramos  (*thank you hramos!*)

**Comment by hramos** [comment]
@ibrahimab a PR was already opened against `facebook/react-native` to do just that: https://github.com/facebook/react-native/pull/19265. It was merged about three weeks ago, and is now part of the `0.56.0-rc` release candidate that we published yesterday.

Please give the RC a try and let us know if the issue is resolved. I'm going to look through @orta's repo and see if there's anything else we need to pull in, but feel free to send a PR if you have a specific fix in mind already.

**Comment by jeffzing** [comment]
"react": "16.4.1",
    "react-native": "^0.56.0",
In file included from /Users/Pods/libsodium/src/libsodium/crypto_aead/aes256gcm/aesni/aead_aes256gcm_aesni.c:19:


still having this ,drive me crazy

**Comment by lamdan** [comment]
@jeffzing i ran into this as well with NAChloride/libsodium. I finally fixed it by setting the Header Search Paths for the libsodium target to only: 

`"${PODS_ROOT}/Headers/Private/libsodium"
"${PODS_ROOT}/Headers/Public/NAChloride"
"${PODS_ROOT}/Headers/Public/libsodium"
"$(PODS_ROOT)/libsodium/src/libsodium/include/sodium"
"$(PODS_ROOT)/libsodium/src/libsodium/include"`

and setting "Use Header Maps" to "No".

**Comment by jeffzing** [comment]
@lamdan infact this is a problem with cocoapods,i build lib of sodium.a without pod then everything works fine.It's a config.h file cross reference issue.anyway thank you guys.

**Comment by jeffzing** [comment]
if there anyone need libsodium.a,let me know

**Comment by chelovekdrakon** [comment]
> ${PODS_ROOT}/Headers/Public/libsodium

It means after "reinstall" of the app: pod install etc. --> you reset this setting?)

I also use NAChloride and run into this issue :/

**Comment by chelovekdrakon** [comment]
@lamdan maybe you found a better way to solve it? :)

**Comment by NickGerleman** [comment]
It looks like this issue regards building an older version of react-native. Please reopen in the `react-native` repo if you experience the problem with a more recent version.
