### ISSUE TITLE
YogaKitSample is neglected and buggy

### ISSUE THREAD

**Issue by mulle-kybernetik-tv** [facebook/yoga#869]
# Report

It seems the YogaKitSample project is very neglected. It doesn't build and it produces faulty layouts.
 
# Issues and Steps to Reproduce

Edit `Podfile` to actually use the local `Yoga` and not some ancient version (1.9.0 that would be), which won't work, because of a missing function:

```
use_frameworks!

target 'YogaKitSample' do
  pod 'Yoga', :path => '../../Yoga.podspec'
  pod 'YogaKit', :path => '../../YogaKit.podspec'
  pod 'IGListKit', '~> 2.1.0'
end
```

Run `pod install` to get a new xcworkspace file.
Run example in iPhone8 Plus 11.4 Simulator. Click on "Basic Layout".

# Expected Behavior

Expected to see something reasonable.

# Actual Behavior

But instead see this:

<img width="526" alt="grafik" src="https://user-images.githubusercontent.com/38703833/53842170-0784bb80-3f9f-11e9-9e2f-25f2fb966186.png">

**Comment by cntrump** [comment]
Fixed in my PR: https://github.com/facebook/yoga/pull/1026

**Comment by philipbel** [comment]
@cntrump PR #1026 has not been merged. The sample is still buggy. This can be quite off-putting to people considering YogaKit.
